@startmindmap
+ punctuation
++ arithmetic
+++_ + plus
+++_ - minus
+++_ * multiply
+++_ / divide
+++_ % or MOD modulus
+++_ UMOD  unsigned modulus
-- comparison
---_ "= equal
---_ <> not equal
-- relational
---_ < or S< less than
---_ > or S> greater than
---_ <= or S<= less than or equal
---_ >= or S>= greater than or equal
---_ && logical and
---_ <Ub+007C> <U+007C> logical or
++ bitwise
+++_ << Shift Left
+++_ >> Shift Right
+++_ {{ Rotate Left
+++_ }} Rotate Right
+++_ NOT(a) 1's Complement
+++_ & Bitwise AND
+++_ | Bitwise OR
+++_ ^ Bitwise XOR
+++_ ^ xor
+++_ & and
+++_ | or
+++_ ! not
-- assignment
---_ "= assignment"
++ grouping
+++ { }
++++_ compound statement
+++ [ ]
++++_ array index
++++_ array initialization
+++ ( )
++++_ function call
++++_ expression grouping
++++_ function declarator
++++_ if, switch, while, do-while, for: delimit controlling clause
++ structure
+++ ;
++++_ statement terminator
++++_ structure terminator
+++ .
++++_ member access
+++ ,
++++_ comma operator
++++_ array separator
++++_ argument list separator
++++_ parameter list separator 





@endmindmap